name: Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  depoy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        environment: ${{ fromJson(
          github.event_name == 'workflow_dispatch' && '[${{ inputs.environment }}]' || '["staging", "production"]') }}
      max-parallel: 1

    environment: ${{ matrix.environment }}

    env:
      DOCKER_TAG: ${{ matrix.environment == 'production' && 'latest' || 'edge' }}
      DOCKER_REGISTRY: ghcr.io
      DOCKER_NAMESPACE: ${{ github.repository_owner }}
      DOCKER_EXTRA_ARGS: --label org.opencontainers.image.source=https://github.com/${{ github.repository }} --cache-from type=gha,mode=max --cache-to type=gha,mode=max

    steps:
      - uses: actions/checkout@v4

      - name: Log into registry ${{ env.DOCKER_REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./actions/infra-build-images
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          namespace: ${{ env.DOCKER_NAMESPACE }}
          docker-tag: ${{ env.DOCKER_TAG }}
          extra-args: --push ${{ env.DOCKER_EXTRA_ARGS }}
